package ru.rmntim.web.tools;

import ru.rmntim.web.models.Point;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class DBCommunicator implements Serializable {

    private static final String DEFAULT_URL = "jdbc:oracle:thin:@//localhost:1521/XEPDB1";
    private static final String DEFAULT_USER = "system";
    private static final String DEFAULT_PASSWORD = "oracle";

    private final String url;
    private final String user;
    private final String password;
    private final String driverClass;

    private static volatile DBCommunicator instance;

    public static DBCommunicator getInstance() {
        DBCommunicator localInstance = instance;
        if (localInstance == null) {
            synchronized (DBCommunicator.class) {
                localInstance = instance;
                if (localInstance == null) {
                    instance = localInstance = new DBCommunicator();
                }
            }
        }
        return localInstance;
    }

    private DBCommunicator() {
        url = Optional.ofNullable(System.getenv("DB_URL")).orElse(DEFAULT_URL);
        user = Optional.ofNullable(System.getenv("DB_USER")).orElse(DEFAULT_USER);
        password = Optional.ofNullable(System.getenv("DB_PASSWORD")).orElse(DEFAULT_PASSWORD);
        driverClass = Optional.ofNullable(System.getenv("DB_DRIVER")).orElse("oracle.jdbc.OracleDriver");

        try {
            Class.forName(driverClass);
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("JDBC driver not found: " + driverClass, e);
        }
        initSchema();
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    private void initSchema() {
        String ddlTable = """
                CREATE TABLE points (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                    x NUMBER(18, 6) NOT NULL,
                    y NUMBER(18, 6) NOT NULL,
                    r NUMBER(18, 6) NOT NULL,
                    inside_area NUMBER(1) NOT NULL,
                    checked_at TIMESTAMP NOT NULL,
                    execution_time NUMBER(18) NOT NULL,
                    CONSTRAINT points_pk PRIMARY KEY (id)
                )
                """;

        try (Connection connection = getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate(ddlTable);
        } catch (SQLException ignored) {
            // ORA-00955: name is already used by an existing object — таблица уже есть, продолжаем
        }
    }

    public void sendOne(Point point) {
        String sql = "INSERT INTO points (x, y, r, inside_area, checked_at, execution_time) VALUES (?, ?, ?, ?, ?, ?)";
        try (Connection connection = getConnection();
             PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            statement.setBigDecimal(1, point.getX());
            statement.setBigDecimal(2, point.getY());
            statement.setBigDecimal(3, point.getR());
            statement.setInt(4, point.isInsideArea() ? 1 : 0);
            statement.setTimestamp(5, new Timestamp(point.getTimestamp().getTime()));
            statement.setLong(6, point.getExecutionTime());
            statement.executeUpdate();
            try (ResultSet keys = statement.getGeneratedKeys()) {
                if (keys.next()) {
                    point.setId(keys.getLong(1));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public ArrayList<Point> getAll() {
        List<Point> result = new ArrayList<>();
        String sql = "SELECT id, x, y, r, inside_area, checked_at, execution_time FROM points ORDER BY id";

        try (Connection connection = getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                Point point = new Point(rs.getBigDecimal("x"), rs.getBigDecimal("y"), rs.getBigDecimal("r"));
                point.setId(rs.getLong("id"));
                point.setInsideArea(rs.getInt("inside_area") == 1);
                point.setTimestamp(rs.getTimestamp("checked_at"));
                point.setExecutionTime(rs.getLong("execution_time"));
                result.add(point);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return new ArrayList<>(result);
    }

    public void clearAll() {
        try (Connection connection = getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("DELETE FROM points");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
